fix : dev 환경 yml 추가

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -2,7 +2,7 @@ name: Auto Merge, Build, and Deploy using Docker Compose
 
 on:
   schedule:
-    - cron: '00 15 * * *'
+    - cron: '05 3 * * *' # 매일 03:05 (UTC 기준)
   workflow_dispatch: # 수동 실행 가능
 
 permissions:
@@ -22,10 +22,12 @@ jobs:
           token: ${{ secrets.MY_GITHUB_TOKEN }}
           submodules: true
 
+
       - name: Configure Git
         run: |
           git config --global user.email "ppuding3861@gmail.com"
           git config --global user.name "ppudding3861"
+
 
       - name: Check for new commits in feat/* branches
         id: check_commits
@@ -37,6 +39,7 @@ jobs:
           else
             echo "has_new_commits=true" >> $GITHUB_ENV
           fi
+
 
       - name: Create or Find PRs from feat/* branches to dev
         if: env.has_new_commits == 'true'
@@ -51,6 +54,7 @@ jobs:
             fi
           done
 
+
       - name: Auto-merge pull requests
         if: env.has_new_commits == 'true'
         env:
@@ -64,11 +68,13 @@ jobs:
             fi
           done
 
+
       - name: Install Docker Compose
         run: |
           sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
           sudo chmod +x /usr/local/bin/docker-compose
           docker-compose version
+
 
       - name: Log in to Docker Hub
         if: env.has_new_commits == 'true'
@@ -78,22 +84,23 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Build and push Docker image using Docker Compose
+        if: env.has_new_commits == 'true'
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
-          S3_FILE_KEYY: ${{ secrets.S3_FILE_KEYY }} # S3_FILE_KEYY 전달
+          S3_FILE_KEY: ${{ secrets.S3_FILE_KEYY }}
+
         run: |
           git fetch origin dev
           git checkout dev
           git pull origin dev
 
-          # Build the Docker image for the local environment
-          docker compose -f docker-compose.local.yml build narrativa_backend_dev
-          docker tag narrativa_backend_dev:latest ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
   
+          docker-compose build narrativa-backend
+          docker tag narrativa-backend:latest ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
 
   deploy_local:
     runs-on: self-hosted
@@ -110,9 +117,10 @@ jobs:
         shell: cmd
         continue-on-error: true
         run: |
-          docker stop narrativa_backend_dev 2>NUL || echo "Container not running or already stopped"
-          docker rm narrativa_backend_dev 2>NUL || echo "Container not found or already removed"
-          docker rmi ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest 2>NUL || echo "Image not found or already removed"
+          docker stop narrativa_backend 2>NUL || echo "Container not running or already stopped"
+          docker rm narrativa_backend 2>NUL || echo "Container not found or already removed"
+          docker rmi ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest 2>NUL || echo "Image not found or already removed"
+      
 
       - name: Pull Docker image from Docker Hub and run container
         shell: cmd
@@ -121,8 +129,14 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
-          S3_FILE_KEYY: ${{ secrets.S3_FILE_KEYY }}
-          S3_FILE_KEY_OVERRIDE: ${{ secrets.S3_FILE_KEYY }}
+          S3_FILE_KEY: ${{ secrets.S3_FILE_KEYY }}
         run: |
-          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
-          docker run -d -p 8080:8080 --name narrativa_backend_dev ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
+          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+          docker run -d -p 8080:8080 --name narrativa_backend ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+  
+  
+  
+  
+  
+  
+  
