feat: task

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -106,7 +106,6 @@ jobs:
     runs-on: self-hosted
     needs: auto_merge_build_deploy
     if: needs.auto_merge_build_deploy.outputs.has_new_commits == 'true'
-
     steps:
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
@@ -114,24 +113,25 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Remove existing containers and images
+      - name: Remove existing Docker container and image
         shell: cmd
         run: |
-          docker-compose down || echo "No containers to remove or an error occurred"
-          docker image rm ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest || echo "No images to remove or an error occurred"
+          docker stop narrativa_backend 2>NUL || echo "Container not running or already stopped"
+          docker rm narrativa_backend 2>NUL || echo "Container not found or already removed"
+          docker rmi ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest 2>NUL || echo "Image not found or already removed"
 
-      - name: Pull Docker image from Docker Hub and run using Docker Compose
-        working-directory: .
+      - name: Pull Docker image from Docker Hub and run container
+        shell: cmd
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
           S3_FILE_KEY: ${{ secrets.S3_FILE_KEY }}
-        shell: cmd
         run: |
-          docker-compose pull narrativa-backend || echo "Error pulling the Docker image"
-          docker-compose up -d || echo "Error starting containers"
+          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+          docker run -d -p 8080:8080 --name narrativa_backend ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+  
   
   
   
