fix : dev 환경 yml 추가

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -2,7 +2,7 @@ name: Auto Merge, Build, and Deploy using Docker Compose
 
 on:
   schedule:
-    - cron: '05 3 * * *' # 매일 03:05 (UTC 기준)
+    - cron: '00 15 * * *'
   workflow_dispatch: # 수동 실행 가능
 
 permissions:
@@ -98,9 +98,9 @@ jobs:
           git pull origin dev
 
   
-          docker-compose build narrativa_backend_dev
-          docker tag narrativa-backend:latest ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
-          docker push ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
+          docker-compose build narrativa-backend
+          docker tag narrativa-backend:latest ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+          docker push ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
 
   deploy_local:
     runs-on: self-hosted
@@ -117,9 +117,9 @@ jobs:
         shell: cmd
         continue-on-error: true
         run: |
-          docker stop narrativa_backend_dev 2>NUL || echo "Container not running or already stopped"
-          docker rm narrativa_backend_dev 2>NUL || echo "Container not found or already removed"
-          docker rmi ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest 2>NUL || echo "Image not found or already removed"
+          docker stop narrativa_backend 2>NUL || echo "Container not running or already stopped"
+          docker rm narrativa_backend 2>NUL || echo "Container not found or already removed"
+          docker rmi ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest 2>NUL || echo "Image not found or already removed"
       
 
       - name: Pull Docker image from Docker Hub and run container
@@ -131,8 +131,8 @@ jobs:
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
           S3_FILE_KEY: ${{ secrets.S3_FILE_KEYY }}
         run: |
-          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
-          docker run -d -p 8080:8080 --name narrativa_backend_dev ${{ secrets.DOCKER_USERNAME }}/narrativa_backend_dev:latest
+          docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
+          docker run -d -p 8080:8080 --name narrativa_backend ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
   
   
   
