feat: task

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -114,45 +114,24 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Pull Docker image from Docker Hub
-        shell: pwsh
+      - name: Remove existing containers and images
+        shell: cmd
         run: |
-          try {
-            docker pull ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest
-            Write-Output "Successfully pulled the latest Docker image"
-          } catch {
-            Write-Output "Error pulling the Docker image: $_"
-            exit 1
-          }
+          docker-compose down || echo "No containers to remove or an error occurred"
+          docker image rm ${{ secrets.DOCKER_USERNAME }}/narrativa_backend:latest || echo "No images to remove or an error occurred"
 
-      - name: Remove existing containers
-        shell: pwsh
-        run: |
-          try {
-            docker-compose down
-            Write-Output "Successfully stopped and removed containers"
-          } catch {
-            Write-Output "No containers to remove or an error occurred: $_"
-          }
-
-      - name: Run containers using Docker Compose
-        shell: pwsh
+      - name: Pull Docker image from Docker Hub and run using Docker Compose
+        working-directory: .
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
           S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
           S3_FILE_KEY: ${{ secrets.S3_FILE_KEY }}
+        shell: cmd
         run: |
-          try {
-            docker-compose up -d
-            Write-Output "Successfully started containers using Docker Compose"
-          } catch {
-            Write-Output "Error starting containers: $_"
-            exit 1
-          }
-  
-  
+          docker-compose pull narrativa-backend || echo "Error pulling the Docker image"
+          docker-compose up -d || echo "Error starting containers"
   
   
   
